In [24]:
import numpy as np

In [25]:
an_array = np.array( [ [1,2,3] , [4,5,6] ,[7,8,9] ])
an_array
           

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [26]:
arr_2 = np.transpose(an_array)

In [27]:
multiplied_array = arr_2 * 2

print(multiplied_array)

[[ 2  8 14]
 [ 4 10 16]
 [ 6 12 18]]


In [29]:
new_array = np.array([1,2,3] , dtype = np.complex128)

In [30]:
new_array.itemsize

16

In [37]:
question5_array = np.array([1,2,3,4,5,6,7,8,9])

In [42]:
question5_array[5:]

array([6, 7, 8, 9])

In [36]:
question6_array = np.array([1,2.5, 'three'])
question6_array.dtype

dtype('<U32')

In [69]:
a = np.arange(6).reshape(3,2)
a

array([[0, 1],
       [2, 3],
       [4, 5]])

In [72]:
b = np.arange(2).reshape(2,)
b

array([0, 1])

In [73]:
a + b

array([[0, 2],
       [2, 4],
       [4, 6]])