## Instructions


*   You can complete the assignment in Jupyter/Colab
*   If you are using Colab, make a copy of the notebook in your own drive
*   To make a submission - 
  *  Run cells such that relevant outputs are visible
  *  Download the source ipynb file for submission
  *  Upload to gradescope






### 0. Import Numpy


In [1]:
import numpy as np #ToDo

### 1. Random array

Generate an integer random numpy array, A, of shape (3,5) with elements from 5 to 26(inclusive). Print the generated random array. (Hint: Look at the documentation of `numpy.random.randint`) [1 pt]

In [2]:
a = np.random.randint(5,27 , size=(3,5)) #ToDo
a

array([[16, 15, 17, 11, 19],
       [26, 11,  5,  7, 21],
       [10, 22, 11, 17, 15]])

### 2. Transpose and inverse of the array `A` 

1. The transpose of an array is created by using the first row of the array as the first column of the new array, the second row of the array as the second column of the new array, and so on. **Print the transpose of A using numpy.** Note - you should not write your own transpose function for this step. [0.5 pt]

For eg. The transpose of 

    x = array([[26,  9, 24,  7, 15],
              [17, 15, 21, 18, 24],
              [ 5, 15, 10, 15, 13]])

    xT = array([[26, 17,  5],
                [ 9, 15, 15],
                [24, 21, 10],
                [ 7, 18, 15],
               [15, 24, 13]])

In [3]:
aT = np.transpose(a) #ToDo
aT

array([[16, 26, 10],
       [15, 11, 22],
       [17,  5, 11],
       [11,  7, 17],
       [19, 21, 15]])

2. Generate a integer random numpy array B, of shape (2,2) with elements from 5 to 12(inclusive). Print B.

In [4]:
b = np.random.randint(5,13 , size=(2,2))#ToDo
b

array([[11,  6],
       [12,  8]])

Like numbers, matrices do have reciprocals. In case of matrices, this reciprocal is called inverse matrix. If A is a square matrix and B is its inverse, then the product of two matrices is equal to the unit matrix. **Print the inverse of B using numpy.** (Hint: look up documentation for linalg library in numpy) [0.5 pt]

For eg. 
      
      Inverse of 
      x=array([[10,  6],
              [ 5,  5]])
       
      x_inv=array([[ 0.25, -0.3 ],
                  [-0.25,  0.5 ]])


In [5]:
b_inv = np.linalg.inv(b) #ToDo
b_inv

array([[ 0.5   , -0.375 ],
       [-0.75  ,  0.6875]])

### 3. Array slicing
1. Slicing in python means taking elements from one given index to another given index. **Print the last 2 columns of array A.** [0.5 pt]

For eg. for the above array A - the last 2 columns are

    array([[ 7, 15],
            [18, 24],
            [15, 13]])

In [6]:
print (a[:, 3:5] )#ToDo

[[11 19]
 [ 7 21]
 [17 15]]


2. Print the 2nd and 3rd rows of array A.  [0.5 pt]

For eg. for the above array A, the 2nd and 3rd rows are

      array([[17, 15, 21, 18, 24],
            [ 5, 15, 10, 15, 13]])

In [7]:
print ( a[1:3 , :])#ToDo

[[26 11  5  7 21]
 [10 22 11 17 15]]


### 4. Broadcasting

1. Broadcasting describes how NumPy treats arrays with different shapes during arithmetic operations. Subject to certain constraints, the smaller array is “broadcast” across the larger array so that they have compatible shapes. Below you can see the difference between vector addition for traditional lists and numpy arrays.




In [8]:
# If we were not using numpy arrays, we would have to loop through the array. Run this cell.
arr= [[27, 11, 27, 11, 20],
       [18, 17, 24, 22, 29],
       [ 6, 17, 13, 19, 18]]
c= [1,2,3,4,5]
for row in range(len(arr)):
  for col in range(len(arr[0])):
    arr[row][col] = arr[row][col]+c[col]
arr

[[28, 13, 30, 15, 25], [19, 19, 27, 26, 34], [7, 19, 16, 23, 23]]


**Create a vector `c=[1,2,3,4,5]`. Add this vector to array `a` using numpy broadcasting. Print the result.**  [0.5 pt]

For eg. for the array A - the result array would be

    array([[27, 11, 27, 11, 20],
          [18, 17, 24, 22, 29],
          [ 6, 17, 13, 19, 18]])



In [9]:
c = np.array([[1, 2 ,3, 4, 5] ] )#ToDo
a + c

array([[17, 17, 20, 15, 24],
       [27, 13,  8, 11, 26],
       [11, 24, 14, 21, 20]])

2. **(True / False) Is it possible to add array b to a? Explain why?**  [0.5 pt]

False. This is not possible since is a size (3,5) and b is size (2,2). These sizes cannot be broadcoasted to each other. If B was size (3,1), it could be broadcasted. The other possibility is the size of c which is (1,5). 

### 5. Reshaping

**Create a list `B=[1,2,3]` and add it to all the columns of `a`. Print the resulting array** (Hint: Use reshape and broadcasting)  [1 pt]

For eg. for the modified array A, the result would be

    array([[28, 12, 28, 12, 21],
          [20, 19, 26, 24, 31],
          [ 9, 20, 16, 22, 21]])

In [10]:
b = [1,2,3] #ToDo
b = np.array(b).reshape(3,1)
a + b

array([[17, 16, 18, 12, 20],
       [28, 13,  7,  9, 23],
       [13, 25, 14, 20, 18]])

### 6. Data analysis using numpy

**Normalization: Substract mean from each row of array `a`. Print the result array.**. (Hint: look at numpy's mean method and it's arguments) [2 pt]

For eg. for the modified array A, the expected output would be

    array([[ 7.8, -8.2,  7.8, -8.2,  0.8],
          [-4. , -5. ,  2. ,  0. ,  7. ],
          [-8.6,  2.4, -1.6,  4.4,  3.4]])

In [11]:
a_mean = a.mean(axis= 1) #ToDo
a_mean = a_mean.reshape(3,1)
a - a_mean

array([[ 0.4, -0.6,  1.4, -4.6,  3.4],
       [12. , -3. , -9. , -7. ,  7. ],
       [-5. ,  7. , -4. ,  2. ,  0. ]])

### 7. Data manipulation in numpy arrays.

**Swap first and second row of array `a`. Print the result array.** [0.5 pt] 

For eg. for the modified array `a` the expected output would be

    array([[20, 19, 26, 24, 31],
          [28, 12, 28, 12, 21],
          [ 9, 20, 16, 22, 21]])


In [12]:
a[ [0,1],: ] = a[ [1,0],: ]#ToDo
a

array([[26, 11,  5,  7, 21],
       [16, 15, 17, 11, 19],
       [10, 22, 11, 17, 15]])

**Swap second and third column of array `a`. Print the result array.**  [0.5 pt]

For eg. for the modified array `a` the expected output would be
   
    array([[20, 26, 19, 24, 31],
          [28, 28, 12, 12, 21],
          [ 9, 16, 20, 22, 21]])

In [13]:
a[ :,[1,2] ] = a[ :,[2,1] ]#ToDo
a

array([[26,  5, 11,  7, 21],
       [16, 17, 15, 11, 19],
       [10, 11, 22, 17, 15]])

### The Power Of Numpy

In [14]:
#Run this cell
import time

In [15]:
#Run this cell
twoD_list = [[i for i in range(500)] for j in range(500)]

In [16]:
#Run this cell
#This a traditional matrix multiplication using for loops
def matrix_multiplication(x, y):
    dp = 0
    prod=[]
    for i in range(len(x)):
      row=[]
      for j in range(len(x[0])):
        mul=0
        for k in range(len(x[0])):
          mul += (x[i][k]*y[k][j])
        row.append(mul)
      prod.append(row)
      
    return prod

In [17]:
#Run this cell. Note the time taken to perform traditional matrix multiplication using lists.
start_time=time.time()
dot_product_list = matrix_multiplication(twoD_list, twoD_list)
end_time=time.time()
print(end_time-start_time)

14.75593876838684


**Convert the `twoD_list` to a numpy array `numpy_twoD_array`. Print the numpy array**

For eg. 

    numpy_twoD = array([[  0,   1,   2, ..., 497, 498, 499],
                        [  0,   1,   2, ..., 497, 498, 499],
                        [  0,   1,   2, ..., 497, 498, 499],
                         ...,
                        [  0,   1,   2, ..., 497, 498, 499],
                        [  0,   1,   2, ..., 497, 498, 499],
                        [  0,   1,   2, ..., 497, 498, 499]])

In [18]:
numpy_twoD_array= np.array(twoD_list)#ToDo
numpy_twoD_array

array([[  0,   1,   2, ..., 497, 498, 499],
       [  0,   1,   2, ..., 497, 498, 499],
       [  0,   1,   2, ..., 497, 498, 499],
       ...,
       [  0,   1,   2, ..., 497, 498, 499],
       [  0,   1,   2, ..., 497, 498, 499],
       [  0,   1,   2, ..., 497, 498, 499]])

**Perform matrix multiplication of the numpy array i.e. numpy_twoD_array * numpy_twoD_array. Record and report the time taken for the operation similar to traditional list multiplication.**  [2 pt]



In [19]:
start_time=time.time();
matrix_mult = np.matmul(numpy_twoD_array,numpy_twoD_array) # ToDo - Insert matrix multiplication using numpy of num_arr with itself

end_time=time.time();
print(end_time-start_time)

0.30904102325439453
